BACKPORTS: Apply CONFIG_MLX5_ESWITCH check with all configure flags
Issue: 1915583
Change-Id: I187c5fc9c104d2512586d06d73f64c7fb5508cc3
Signed-off-by: Feras Daoud <ferasda@mellanox.com>

diff --git a/ofed_scripts/configure b/ofed_scripts/configure
--- a/ofed_scripts/configure
+++ b/ofed_scripts/configure
@@ -679,12 +679,6 @@ main()
                             CONFIG_MLX5_EN_RXNFC="y"
                             CONFIG_MLX5_MPFS="y"
                             CONFIG_MLX5_ESWITCH="y"
-    if ! check_kerver ${KVERSION} ${SWITCH_SUPPORTED_KVERSION}; then
-        if ! check_kerver_list $KVERSION $SWITCH_SUPPORTED_KVERSION_LIST; then
-                            CONFIG_MLX5_ESWITCH=
-            echo "Error: CONFIG_MLX5_ESWITCH requires kernel version ${SWITCH_SUPPORTED_KVERSION} or higher (current: ${KVERSION})."
-        fi
-    fi
                             CONFIG_MLX5_CORE_IPOIB="y"
                             CONFIG_MLX5_EN_SPECIAL_SQ="y"
                             CONFIG_MLX5_INFINIBAND="m"
@@ -1081,6 +1075,13 @@ if [ -z "$KSRC_OBJ" ]; then
 		KSRC_OBJ=$KSRC
 		KSRC=${sources_dir}
 	fi
+fi
+
+if ! check_kerver ${KVERSION} ${SWITCH_SUPPORTED_KVERSION}; then
+    if ! check_kerver_list $KVERSION $SWITCH_SUPPORTED_KVERSION_LIST; then
+                        CONFIG_MLX5_ESWITCH=
+        echo "Error: CONFIG_MLX5_ESWITCH requires kernel version ${SWITCH_SUPPORTED_KVERSION} or higher (current: ${KVERSION})."
+    fi
 fi
 
 KSRC_OBJ=${KSRC_OBJ:-"$KSRC"}
