mlnx-ofed-kernel-utils.openibd.init: Enable persistent configuration of PF via ECPF
Persistent configuration should be set in /etc/infiniband/openib.conf
In format:
SMARTNIC_PF_MAC_CONF="[<bdf1>-<MAC1>] [<bdf2>-<MAC2>] ..."

E.g.:
SMARTNIC_PF_MAC_CONF="0000:03:00.0-c4:8a:07:a5:29:70 0000:03:00.1-c4:8a:07:a5:29:71"

Issue: 1870464

Change-Id: I2583b1c885a678d671fdc9216dd83cc1b5ac8ba8
Signed-off-by: Vladimir Sokolovsky <vlad@mellanox.com>

diff --git a/ofed_scripts/mlnx-ofed-kernel-utils.openibd.init b/ofed_scripts/mlnx-ofed-kernel-utils.openibd.init
--- a/ofed_scripts/mlnx-ofed-kernel-utils.openibd.init
+++ b/ofed_scripts/mlnx-ofed-kernel-utils.openibd.init
@@ -992,6 +992,34 @@ start()
         RC=$[ $RC + $my_rc ]
     fi
 
+    # Set MAC address of PF via ECPF
+    # SMARTNIC_PF_MAC_CONF="[<bdf1>-<MAC1>] [<bdf2>-<MAC2>] ..."
+    if [ "X${SMARTNIC_PF_MAC_CONF}" != "X" ]; then
+        for mac_conf in ${SMARTNIC_PF_MAC_CONF}
+        do
+            bdf=${mac_conf%%-*}
+            mac=${mac_conf##*-}
+            if [ ! -d /sys/bus/pci/devices/${bdf}/ ]; then
+                log_msg "No such device: ${bdf}."
+                log_msg "Check SMARTNIC_PF_MAC_CONF value in the $CONFIG"
+                continue
+            fi
+            for i in `/bin/ls -1 /sys/bus/pci/devices/${bdf}/net 2> /dev/null`
+            do
+                if [ -e /sys/bus/pci/devices/${bdf}/net/${i}/smart_nic/pf/mac ]; then
+                    echo $mac > /sys/bus/pci/devices/${bdf}/net/${i}/smart_nic/pf/mac
+                    my_rc=$?
+                    if [ $my_rc -eq 0 ]; then
+                        log_msg "PF MAC is set to $mac via ECPF $i"
+                    else
+                        log_msg "ERROR: Failed to set MAC $mac via ECPF $i"
+                    fi
+                    RC=$[ $RC + $my_rc ]
+                fi
+            done
+        done
+    fi
+
     if [ -x /sbin/mlnx_eswitch_set  ]; then
         /sbin/mlnx_eswitch_set
     fi
